sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 173521
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  wechat:
    appid: wxd0e4c8d9ef06ab1c
    secret: 4119ff288604cec6c1c1ac0e9eb7a77c